- name: multi level variables
  hosts: localhost
  # vars:
  #   value: value from play level
  # vars_files:
  #   - vars.yaml
  # vars_prompt:
  #   name: value
  #   prompt: enter value is from prompt
  #   private: false
  tasks:
  - name: print variable value
    # vars:
    #   value: value from task level
    ansible.builtin.debug:
     msg: "the value of the variable is : {{ value | default('sundar') }}" 

     # 01-command line
     # 02-task level
     # 03-file level
     # 04-prompt level
     # 05-play level
